export const countryIdToName: Record<string, string> = {
    albania: "Albania",
    armenia: "Armenia",
    austria: "Austria",
    azerbaijan: "Azerbaijan",
    belarus: "Belarus",
    belgium: "Belgium",
    "bosnia-and-herzegovina": "Bosnia and Herzegovina",
    bulgaria: "Bulgaria",
    china: "China",
    croatia: "Croatia",
    czechia: "Czechia",
    denmark: "Denmark",
    egypt: "Egypt",
    estonia: "Estonia",
    ethiopia: "Ethiopia",
    finland: "Finland",
    france: "France",
    georgia: "Georgia",
    germany: "Germany",
    greece: "Greece",
    "hong-kong": "Hong Kong",
    hungary: "Hungary",
    italy: "Italy",
    japan: "Japan",
    latvia: "Latvia",
    lebanon: "Lebanon",
    macau: "Macau",
    madagascar: "Madagascar",
    malaysia: "Malaysia",
    mali: "Mali",
    malta: "Malta",
    monaco: "Monaco",
    mongolia: "Mongolia",
    montenegro: "Montenegro",
    morocco: "Morocco",
    netherlands: "Netherlands",
    "north-macedonia": "North Macedonia",
    norway: "Norway",
    portugal: "Portugal",
    qatar: "Qatar",
    romania: "Romania",
    russia: "Russia",
    serbia: "Serbia",
    singapore: "Singapore",
    slovakia: "Slovakia",
    slovenia: "Slovenia",
    "south-korea": "South Korea",
    spain: "Spain",
    sweden: "Sweden",
    switzerland: "Switzerland",
    syria: "Syria",
    thailand: "Thailand",
    tunisia: "Tunisia",
    turkey: "Turkey",
    ukraine: "Ukraine",
    "united-arab-emirates": "United Arab Emirates",
    "united-kingdom": "United Kingdom",
    "vatican-city": "Vatican City",
  
    andorra: "Andorra",
    argentina: "Argentina",
    bahrain: "Bahrain",
    bangladesh: "Bangladesh",
    bhutan: "Bhutan",
    bolivia: "Bolivia",
    brunei: "Brunei",
    cambodia: "Cambodia",
    canada: "Canada",
    chile: "Chile",
    colombia: "Colombia",
    "costa-rica": "Costa Rica",
    cuba: "Cuba",
    ecuador: "Ecuador",
    "el-salvador": "El Salvador",
    fiji: "Fiji",
    ghana: "Ghana",
    guatemala: "Guatemala",
    honduras: "Honduras",
    iceland: "Iceland",
    india: "India",
    indonesia: "Indonesia",
    iran: "Iran",
    iraq: "Iraq",
    ireland: "Ireland",
    israel: "Israel",
    jordan: "Jordan",
    kazakhstan: "Kazakhstan",
    kenya: "Kenya",
    kuwait: "Kuwait",
    kyrgyzstan: "Kyrgyzstan",
    laos: "Laos",
    libya: "Libya",
    lithuania: "Lithuania",
    luxembourg: "Luxembourg",
    mauritius: "Mauritius",
    mexico: "Mexico",
    moldova: "Moldova",
    myanmar: "Myanmar",
    namibia: "Namibia",
    nepal: "Nepal",
    "new-zealand": "New Zealand",
    nicaragua: "Nicaragua",
    oman: "Oman",
    pakistan: "Pakistan",
    panama: "Panama",
    paraguay: "Paraguay",
    peru: "Peru",
    philippines: "Philippines",
    poland: "Poland",
    "saudi-arabia": "Saudi Arabia",
    senegal: "Senegal",
    "south-africa": "South Africa",
    "sri-lanka": "Sri Lanka",
    tajikistan: "Tajikistan",
    tanzania: "Tanzania",
    "timor-leste": "Timor-Leste",
    togo: "Togo",
    "trinidad-and-tobago": "Trinidad and Tobago",
    turkmenistan: "Turkmenistan",
    uganda: "Uganda",
    "united-states": "United States",
    uruguay: "Uruguay",
    uzbekistan: "Uzbekistan",
    venezuela: "Venezuela",
    vietnam: "Vietnam",
    yemen: "Yemen",
    zambia: "Zambia",
    zimbabwe: "Zimbabwe",
    taiwan: "Taiwan",
    greenland: "Greenland",
    "faroe-islands": "Faroe Islands",
    "puerto-rico": "Puerto Rico",
    guam: "Guam",
    aruba: "Aruba",
    "french-polynesia": "French Polynesia",
  };