const countryFlags: Record<string, string> = {
    Afghanistan: "🇦🇫",
    Albania: "🇦🇱",
    Algeria: "🇩🇿",
    Andorra: "🇦🇩",
    Angola: "🇦🇴",
    Argentina: "🇦🇷",
    Armenia: "🇦🇲",
    Australia: "🇦🇺",
    Austria: "🇦🇹",
    Azerbaijan: "🇦🇿",
  
    Bahrain: "🇧🇭",
    Bangladesh: "🇧🇩",
    Belarus: "🇧🇾",
    Belgium: "🇧🇪",
    Belize: "🇧🇿",
    Benin: "🇧🇯",
    Bhutan: "🇧🇹",
    Bolivia: "🇧🇴",
    "Bosnia and Herzegovina": "🇧🇦",
    Botswana: "🇧🇼",
    Brazil: "🇧🇷",
    Brunei: "🇧🇳",
    Bulgaria: "🇧🇬",
    "Burkina Faso": "🇧🇫",
    Burundi: "🇧🇮",
  
    Cambodia: "🇰🇭",
    Cameroon: "🇨🇲",
    Canada: "🇨🇦",
    Chad: "🇹🇩",
    Chile: "🇨🇱",
    China: "🇨🇳",
    Colombia: "🇨🇴",
    Comoros: "🇰🇲",
    Congo: "🇨🇬",
    "Costa Rica": "🇨🇷",
    Croatia: "🇭🇷",
    Cuba: "🇨🇺",
    Cyprus: "🇨🇾",
    Czechia: "🇨🇿",
  
    Denmark: "🇩🇰",
    Djibouti: "🇩🇯",
    "Dominican Republic": "🇩🇴",
  
    Ecuador: "🇪🇨",
    Egypt: "🇪🇬",
    "El Salvador": "🇸🇻",
    Estonia: "🇪🇪",
    Eswatini: "🇸🇿",
    Ethiopia: "🇪🇹",
  
    Fiji: "🇫🇯",
    Finland: "🇫🇮",
    France: "🇫🇷",
  
    Gabon: "🇬🇦",
    Gambia: "🇬🇲",
    Georgia: "🇬🇪",
    Germany: "🇩🇪",
    Ghana: "🇬🇭",
    Greece: "🇬🇷",
    Guatemala: "🇬🇹",
    Guinea: "🇬🇳",
  
    Haiti: "🇭🇹",
    Honduras: "🇭🇳",
    Hungary: "🇭🇺",
  
    Iceland: "🇮🇸",
    India: "🇮🇳",
    Indonesia: "🇮🇩",
    Iran: "🇮🇷",
    Iraq: "🇮🇶",
    Ireland: "🇮🇪",
    Israel: "🇮🇱",
    Italy: "🇮🇹",
    "Ivory Coast": "🇨🇮",
  
    Jamaica: "🇯🇲",
    Japan: "🇯🇵",
    Jordan: "🇯🇴",
  
    Kazakhstan: "🇰🇿",
    Kenya: "🇰🇪",
    Kuwait: "🇰🇼",
    Kyrgyzstan: "🇰🇬",
  
    Laos: "🇱🇦",
    Latvia: "🇱🇻",
    Lebanon: "🇱🇧",
    Lesotho: "🇱🇸",
    Liberia: "🇱🇷",
    Libya: "🇱🇾",
    Lithuania: "🇱🇹",
    Luxembourg: "🇱🇺",
  
    Madagascar: "🇲🇬",
    Malawi: "🇲🇼",
    Malaysia: "🇲🇾",
    Mali: "🇲🇱",
    Malta: "🇲🇹",
    Mauritania: "🇲🇷",
    Mauritius: "🇲🇺",
    Mexico: "🇲🇽",
    Moldova: "🇲🇩",
    Monaco: "🇲🇨",
    Mongolia: "🇲🇳",
    Montenegro: "🇲🇪",
    Morocco: "🇲🇦",
    Mozambique: "🇲🇿",
    Myanmar: "🇲🇲",
  
    Namibia: "🇳🇦",
    Nepal: "🇳🇵",
    Netherlands: "🇳🇱",
    "New Zealand": "🇳🇿",
    Nicaragua: "🇳🇮",
    Niger: "🇳🇪",
    Nigeria: "🇳🇬",
    "North Macedonia": "🇲🇰",
    Norway: "🇳🇴",
  
    Oman: "🇴🇲",
  
    Pakistan: "🇵🇰",
    Panama: "🇵🇦",
    Paraguay: "🇵🇾",
    Peru: "🇵🇪",
    Philippines: "🇵🇭",
    Poland: "🇵🇱",
    Portugal: "🇵🇹",
  
    Qatar: "🇶🇦",
  
    Romania: "🇷🇴",
    Russia: "🇷🇺",
    Rwanda: "🇷🇼",
  
    "Saudi Arabia": "🇸🇦",
    Senegal: "🇸🇳",
    Serbia: "🇷🇸",
    "Sierra Leone": "🇸🇱",
    Singapore: "🇸🇬",
    Slovakia: "🇸🇰",
    Slovenia: "🇸🇮",
    Somalia: "🇸🇴",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    Spain: "🇪🇸",
    "Sri Lanka": "🇱🇰",
    Sudan: "🇸🇩",
    Suriname: "🇸🇷",
    Sweden: "🇸🇪",
    Switzerland: "🇨🇭",
    Syria: "🇸🇾",
  
    Taiwan: "🇹🇼",
    Tajikistan: "🇹🇯",
    Tanzania: "🇹🇿",
    Thailand: "🇹🇭",
    Togo: "🇹🇬",
    Tunisia: "🇹🇳",
    Turkey: "🇹🇷",
    Turkmenistan: "🇹🇲",
  
    Uganda: "🇺🇬",
    Ukraine: "🇺🇦",
    "United Arab Emirates": "🇦🇪",
    "United Kingdom": "🇬🇧",
    "United States": "🇺🇸",
    Uruguay: "🇺🇾",
    Uzbekistan: "🇺🇿",
  
    Venezuela: "🇻🇪",
    Vietnam: "🇻🇳",
  
    Yemen: "🇾🇪",
  
    Zambia: "🇿🇲",
    Zimbabwe: "🇿🇼",
  };
  
  Object.freeze(countryFlags);
  
  export default countryFlags;